spring:
  application:
    name: spring-auth-starter

#  database config
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JwtExpirationMS}
    cookieName: "jwtCookie"
    cookieSecure: ${JWT_COOKIE_SECURE:false}

  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
    
logging:
  level:
    org.springframework: DEBUG
    org.hibernate.sql: DEBUG
    org.springframework.security: TRACE
    com.abdellah.spring_auth_starter: DEBUG